### ISSUE TITLE
SharpOD plugin

### ISSUE THREAD

**Issue by NotNotMarshall** [horsicq/x64dbg-Plugin-Manager#1]
Hello there, please add this plugin to the list too. This is a VMP evader plugin which is the best one to make evasion easy so far ScyllaHide is not working anymore.

Original (updated):
https://forum.tuts4you.com/topic/39806-sharpod-x64-a_antidebug-plugin-support-for-x64dbg/?tab=comments#comment-191644

Old:
https://github.com/A-new/x64dbg_plugin/blob/master/x32/SharpOD%20x64.dp32

**Comment by horsicq** [comment]
Hello! Does this plugin work property on the last version of x64dbg?

**Comment by NotNotMarshall** [comment]
> Hello! Does this plugin work properly on the last version of x64dbg?

Yep it does, I actually use it every time when I work with VMProtected binaries because the latest version of ScyllaHide isn't doing too good with VMP 3.x and above.

**Comment by NotNotMarshall** [comment]
> Hello! Does this plugin work properly on the last version of x64dbg?

The original author of the plugin Xjun releases every update on tuts4you forum from the given link above.

**Comment by horsicq** [comment]
Thanks a lot for the information!

I added this plugin to server list.

Please update server list to see the changes.

![image](https://user-images.githubusercontent.com/7762949/71996161-0914b500-323c-11ea-848b-b8710e03c0e3.png)

**Comment by NotNotMarshall** [comment]
> Thanks a lot for the information!
> 
> I added this plugin to server list.
> 
> Please update server list to see the changes.
> 
![image](https://user-images.githubusercontent.com/23288867/72066256-0d63cf80-331b-11ea-875a-7d56c5bd3dd9.png)

Hello, thank you very much but I'm getting this error.

**Comment by horsicq** [comment]
Thanks for the testing. Please download the archive https://github.com/horsicq/x64dbg-Plugin-Manager/releases/tag/0.02 and replace base/x64plgmnr.exe and base/x64plgmnrc.exe in your x64dbg Plugin Manager's folder.
