### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by konosubakonoakua** [horsicq/x64dbg-Plugin-Manager#12]
![image](https://user-images.githubusercontent.com/42881610/107372097-01e76700-6b20-11eb-96f3-ded0b3f5b4d2.png)

![image](https://user-images.githubusercontent.com/42881610/107372272-322f0580-6b20-11eb-9e3a-eabe85e49370.png)

cannot get plugin list from github

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I'll take a look.
