### ISSUE TITLE
[not an issue] - clarification needed on the x64dbg root path to be inserted in Plugin Manager options

### ISSUE THREAD

**Issue by illtellyoulater** [horsicq/x64dbg-Plugin-Manager#19]
Hello, 
I am setting up your Plugin Manager but I am not sure on what folder I should pick as the x64dbg root folder.

The latest `x64dbg` I've downloaded comes as a file named `snapshot_date-of-build.zip` and when extracting it to a dir, it will contain two subdirs: "/pluginsdk" and "/release", with the latter containing "x96dbg.exe".

Now, should I consider as root the main folder containing /pluginsdk and /release, or simply the /release folder?

Thanks a lot for your help!

**Comment by horsicq** [comment]
Main folder.

**Comment by illtellyoulater** [comment]
I made a quick test giving Plugin Manager just an empty folder, and in there it created the /x32 and /x64 dirs, and within each of those, the /plugins dirs, where the plugins got installed.

So actually Plugin Manager as for the root folder doesn't want the main zip extraction folder containing /pluginSDK and /release, but the /release folder, which is where the /x32 and /64 dirs are located.

So yeah, perhaps to avoid confusion you could just say to the user: "please provide the root dir of x64dbg, the one containing /x32 and /x64 dirs", or something like that.

**Comment by horsicq** [comment]
Ok. Thanks a lot for the idea with the message text. I will think about it.
