### ISSUE TITLE
Plugin Manager shows and downloads old versions of some plugins instead of their actual last versions 

### ISSUE THREAD

**Issue by illtellyoulater** [horsicq/x64dbg-Plugin-Manager#20]
Hello, I made a quick test trying to download the ScyllaHide plugin using your Plugin Manager.

The GUI reports latest version of ScyllaHide to be from 2021-01-26, while the official ScyllaHide repository has a newer release from 2021-08-23.
This will stay the same also after clicking on the "Update Server List" button.

So, does Plugin Manger actually check for latest versions, or does it use hard-coded versions?

**Comment by horsicq** [comment]
Thanks a lot for the report. I will take a look.

**Comment by horsicq** [comment]
Fixed
