### ISSUE TITLE
No waifu

### ISSUE THREAD

**Issue by obama-gaming** [horsicq/x64dbg-Plugin-Manager#27]
Hello I come to software and no waifu? What fix?

**Comment by obama-gaming** [comment]
Since this tool is used by refined members of society. I think the most appropriate attire for the mascot is a top hat + monocle.

**Comment by horsicq** [comment]
// I think the most appropriate attire for the mascot is a top hat + monocle.

Good idea! Any ideas for colors? Or no matter?

**Comment by duxeyo** [comment]
> // I think the most appropriate attire for the mascot is a top hat + monocle.
> 
> Good idea! Any ideas for colors? Or no matter?

lavender is good #babaff

**Comment by horsicq** [comment]
Something like this?

![image](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/199cc7d0-4ef9-4abd-9f31-22525cdf5d1b)

**Comment by duxeyo** [comment]
yes make lavender tho

**Comment by horsicq** [comment]
// yes make lavender tho

Sure. :)

**Comment by pml4** [comment]
![daum](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/69989150/72b89110-b46d-491b-9030-9583e3344616)
I believe this image would be perfect

**Comment by horsicq** [comment]
> I believe this image would be perfect

Great! I will add the top hat and monocle.

**Comment by pml4** [comment]
> > I believe this image would be perfect
> 
> Great! I will add the top hat and monocle.

Thank you. I eagerly await the new waifu sporting a fashionable DAUM shirt.

**Comment by horsicq** [comment]
Could you please choose the style
![IMG_20230818_163221_593](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/6f0ad4db-07d1-423c-a908-8c617bafbfc6)

**Comment by pml4** [comment]
I vote for the second one. But please don't forget the DAUM shirt!

**Comment by horsicq** [comment]
BTW what is "DAUM"?

**Comment by horsicq** [comment]
> daum he friend me and very STRONG reverse

All clear. DAUM is [obama-gaming](https://github.com/obama-gaming) :)

Sorry But it is a mascot for X64dbg Plugin Manager. 

If he will need a mascot for his own project -> I will create it **with pleasure** for him with "DAUM" shirt or without. :)

**Comment by pml4** [comment]
I will cry now, he is my best brother and now he sad so I cry

**Comment by horsicq** [comment]
> I will cry now, he is my best brother. He save my life in war

Brother. This is a wrong place to troll someone.

**Comment by obama-gaming** [comment]
I apologize for the trolls, I haven't kept up with this thread. I really like the second or third one. I use other tools you made, like XPEViewer, Detect It Easy, and more daily. I was really disappointed to see that this tool didn't have a mascot. Its always a joy to use your tools, and the mascot always adds to them.

**Comment by horsicq** [comment]
> I apologize for the trolls, I haven't kept up with this thread. I really like the second or third one. I use other tools you made, like XPEViewer, Detect It Easy, and more daily. I was really disappointed to see that this tool didn't have a mascot. Its always a joy to use your tools, and the mascot always adds to them.

Thank you for using my tools! :)
So I will make the second one!

**Comment by horsicq** [comment]
![1](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/b488b3d9-d851-4902-a964-9396ca284cd3)

**Comment by horsicq** [comment]
![2](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/3a8d3802-45b0-4a2c-bcc8-0626befff82c)

**Comment by horsicq** [comment]
![3](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/6d057322-69f3-4d12-a58c-ba47c345eaeb)

**Comment by horsicq** [comment]
![4](https://github.com/horsicq/x64dbg-Plugin-Manager/assets/7762949/c86eed84-8253-4486-ba18-f90ba957eecb)
