### ISSUE TITLE
which path is the root of x64dbg

### ISSUE THREAD

**Issue by jelasin** [horsicq/x64dbg-Plugin-Manager#28]

**Comment by jelesan** [comment]
when i choose x64dbg\release\x64plgmnr_win32_portable

**Comment by horsicq** [comment]
You should choose it. I am making: C:\x64dbg_root

**Comment by jelesan** [comment]
I got this err : Host raw.githubusercontent.com not found

**Comment by jelesan** [comment]
should I open proxy
