### ISSUE TITLE
Plugin-Manager wants to install CopyToAsm_x64 plugin into x64dbg's 32-bit plugin directory

### ISSUE THREAD

**Issue by TissuePowder** [horsicq/x64dbg-Plugin-Manager#6]
![64dbg_plugin_manager_issue](https://user-images.githubusercontent.com/39616942/94340089-d193a600-0020-11eb-9db0-fc6efdd14aea.png)

If you install the CopyToAsm_x32 plugin first, then trying to installing the _x64 one afterwards does nothing, since the plugin-manager thinks it's already installed.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. Could you try to click "Update server list" and try again?

**Comment by TissuePowder** [comment]
Updating server list has resolved the 64/32 problem, but for some reason the plugin files aren't being downloaded. The downloaded "CopyToAsm_x__.x64dbg.zip" files only contain the plugin_info.json files, the "files" directory that contains the plugins seem to be absent. So the manager can't install anything.
![3_64dbg_plugin_manager_issue](https://user-images.githubusercontent.com/39616942/94342448-e11bea80-0032-11eb-98a9-8eb9abd28133.png)
![2_64dbg_plugin_manager_issue](https://user-images.githubusercontent.com/39616942/94342454-ea0cbc00-0032-11eb-963c-ee1b1bff500f.png)

**Comment by horsicq** [comment]
Thanks for the test!. Could you try to click "Update server list" again.

I changed the server list: https://github.com/x64dbg/PluginManager/commit/c334986db22bfae22762caddc5812da237dda555

**Comment by TissuePowder** [comment]
Just clicking on "Update sever list" doesn't resolve it though. Updating server list saves the new list json file with list.lastest.json name, but the GUI still uses the old file instead of latest file. The latest file has to be renamed and overwritten with the old one, then all good. Anyway, it works like a charm now.

**Comment by horsicq** [comment]
Thanks for the feedback. The problem with server.list will be checked and fixed in the new version of the program
